pre-commit:
  parallel: true
  commands:
    build:
      run: bun run build
      stage_fixed: true
    lint:
      run: bun run lint:fix
      stage_fixed: true
    format:
      run: bun run format:fix
      stage_fixed: true
    test:
      run: bun run test:ci
      stage_fixed: true
